### ISSUE TITLE
New Theme Sidebar in Lights Page

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/home-orchestrator#25]
blocked until overhaul is implemented

### New design for the sidebar

Here's the XD link https://xd.adobe.com/spec/ba142d26-a73c-4b16-6ae7-75526fb5e03a-cc25/

![Screenshot 2019-08-25 at 6 23 00 PM](https://user-images.githubusercontent.com/45569851/63648648-67496b80-c765-11e9-9238-0c098682ac68.png)

Sidebar interactions:
- when a theme is clicked they become a light blue, and submits the theme's setting to make the lights change colours
- circle colours show light's info when hovered over
- edit button on the top right of each theme button directs the user to the 'edit theme' page.

### Future ideas:
We probably want some type of sub menu for our pages to allow us to add more functionality to each section than we can currently support.

## Plan
- [x] design how themes submenu should look on the lights page
- [ ] implement this design
- [ ] deploy to live

**Comment by kyliechung** [comment]
Here are some pics of the sketched wireframes I did. 

Initial thought - Merging the footer and the submenu together
![IMG_3776](https://user-images.githubusercontent.com/45569851/62946079-a2b57300-be12-11e9-994f-e81a3e28e96e.JPG)

Revised sketch - Separated them as we had initially planned for the sidebar to show the catalogue of themes that have been created by the user (The sketch with the star on the top left is the finalised design I'm basing the rest of my designing off of.)
![IMG_3781](https://user-images.githubusercontent.com/45569851/62946075-9f21ec00-be12-11e9-87e5-579c34bf6981.JPG)
I noticed that I've forgotten to add a colour palette to the Themes in the sidebar, so I'll remember to add that in the soft version of the wireframe in the next progress update! 

The pictures have other things going on in the project too, so try to focus on the part that affects this issue.

**Comment by kyliechung** [comment]
Sorry I made a mistake! I had a mix-up and thought that the taskbar in issue #23 was about the menu during the designing process - I guess I went off track there! 
So to clear things up also ignore the bottom menu bar I've drawn out. 
I can circle what we are supposed to be looking at here (the sidebar for the themes) :
![IMG_3781 copy](https://user-images.githubusercontent.com/45569851/62948805-a4ce0080-be17-11e9-8ad1-9b98033175ce.JPG)

**Comment by kyliechung** [comment]
Here's the [link](https://xd.adobe.com/spec/53ca18e1-20bf-41f6-45af-572d03546492-25fb/) to the XD version of the design. 

I had already done the menu earlier from the prior mistake above thinking that it was the Taskbar issue, but I thought I'd reuse it for now as the menu on the site design, as there is nothing really different in terms of its functionality to the one we have now on our current site. The only difference really is the aesthetics.

For clarity reasons, this is a screenshot to show you what I mean by a Theme Palette.
<img width="145" alt="Screen Shot 2019-08-14 at 20 35 27" src="https://user-images.githubusercontent.com/45569851/63021422-233ba880-bed3-11e9-90f0-053cfbcb15c4.png">


For the UX part of this issue, I was thinking that users can click on each Colour-Pickers in their Theme Palettes (like the colour picker we have currently on the site now), because it pops up the Full Colour Wheel Picker - while keeping the site looking minimal and decluttered, but still showing full detail when needed!

This is the Full Colour Wheel Picker that I meant, which pops up after the Colour-Picker has been clicked on.
<img width="334" alt="Screen Shot 2019-08-14 at 20 33 04" src="https://user-images.githubusercontent.com/45569851/63021607-875e6c80-bed3-11e9-8f72-b7289a3feeca.png">


Let me know if there is any improvement suggestion/changes!

**Comment by michaelfitzhavey** [comment]
@kyliechung the design looks lovely, I'm a little unclear about how the sidebar should be interacted though, is each pallete its own button? Or does clicking a theme go ahead and apply it?

**Comment by kyliechung** [comment]
@michaelfitzhavey  Good question, the palettes are buttons that can submit the theme settings and change all the lights in one go. And I was thinking that the individual circle colour-pickers can show info and brightness of the one light in the theme palette, when it is hovered over. 

I've added this information on my comment in the design link above!

I will also try to make a xd version to show what happens when the circle colours are hovered over!

**Comment by michaelfitzhavey** [comment]
I think it's easier if the only actions we can take on a theme are 'apply' or 'edit' (takes you to the theme edit page)

**Comment by kyliechung** [comment]
@michaelfitzhavey that's a really important point I missed out, thanks! I added it to my comment above under "Interaction of the Side Bar elements".
